### ISSUE TITLE
[Question] Harmony

### ISSUE THREAD

**Issue by justinhelmer** [sindresorhus/npm-name-cli#1]
@sindresorhus - Is there something else I need to install globally to take advantage of this tool?

It's complaining about `const`.

```
const logSymbols = require('log-symbols');
^^^^^
SyntaxError: Use of const in strict mode.
```

I tried modifying the hashbang temporarily in `cli.js`:

```bash
#!/usr/bin/env node --harmony
```

... but then it got stuck up on the template string.

Thanks for the insight.

**Comment by sindresorhus** [comment]
Upgrade Node.js.

**Comment by sindresorhus** [comment]
The Node.js version requirement is clearly defined in package.json: https://github.com/sindresorhus/npm-name-cli/blob/3e14ede9f6636454d816e0f8a341a322c9cf4c8c/package.json#L16

**Comment by justinhelmer** [comment]
Yep. sorry for taking your time. Thanks for the quick reply.
