### ISSUE TITLE
Invalid name reported as available

### ISSUE THREAD

**Issue by astur** [sindresorhus/npm-name-cli#11]
```bash
~ $ npm-name _AVA
✔ _AVA is available
```

But such names [are invalid](https://docs.npmjs.com/files/package.json#name). It will be better if npm-name will say something like this:
```bash
✖ _AVA is invalid
```

**Comment by sindresorhus** [comment]
Agreed. This check should be implemented in https://github.com/sindresorhus/npm-name Can you move the issue over there?

**Comment by astur** [comment]
Ok, now there is [#21](https://github.com/sindresorhus/npm-name/issues/21) on [npm-name](https://github.com/sindresorhus/npm-name).

But how can we found is package name invalid (by npm rules) or unavailable?

**Comment by astur** [comment]
@sindresorhus don't you think it is good idea to leave npm-name as is and fix npm-name-cli?

Now npm-name-cli uses npm-name and squatter for checks. I can add [validate-npm-package-name)](https://github.com/npm/validate-npm-package-name) to it. So we'll have difference between 'invalid' and 'unavailable' names. Like this:

```bash
~ $ npm-name c ava _ABC
⚠ c is squatted
✖ ava is unavailable
✔ _ABC is invalid
```

**Comment by sindresorhus** [comment]
npm-name should have the check. We can throw a custom error when the name is invalid and we can handle it specially here.
