### ISSUE TITLE
You can do the same with bash and curl

### ISSUE THREAD

**Issue by devlato** [sindresorhus/npm-name-cli#12]
Hello,

what's the purpose of this library? 😀
You can do the same without having any dependency on `Node` and `npm` at all:

```sh
curl -L -s -o /dev/null -w "%{http_code}" "https://npmjs.org/package/PUT-PACKAGE-NAME-HERE"
```

If it prints 404, the package doesn't exist.

You can even define a command in your `.bashrc` (or whatever shell you use):

```sh
# in .bashrc
npkg() {
  curl -L -s -o /dev/null -w "%{http_code}" "https://npmjs.org/package/$1"
  echo
}

# in shell
$ npkg somenonexistingpackage
404 # Package doesn't exist
$ npkg babel
200 # Package exists!
```

**Comment by sindresorhus** [comment]
![giphy](https://user-images.githubusercontent.com/170270/43306440-524c942e-91a5-11e8-874c-4ab010d9c766.gif)

**Comment by sindresorhus** [comment]
You can do anything in Bash. Doesn't mean I would want to. I don't enjoy Bash, I do enjoy Node.js 😉
