### ISSUE TITLE
Name too similar

### ISSUE THREAD

**Issue by kevincastejon** [sindresorhus/npm-name-cli#21]
Hi, I just tried out this tool and I realized that it tells you if the provided package name **exists** on NPM but **not if it is actually available to publish** on NPM . Because of the similarity between the provided package name and one(s) already existing, that name could be rejected when publishing even if npm-name-cli tells us it is available

**Comment by sindresorhus** [comment]
Yes, this is tracked here: https://github.com/sindresorhus/npm-name/issues/15
