### ISSUE TITLE
Feature request: include (optional?) thesaurus of names relating to the search

### ISSUE THREAD

**Issue by Robbie-Cook** [sindresorhus/npm-name-cli#22]
I think an (optional?) thesaurus of names relating to the search could be useful.

Is this something others are interested in?

e.g. `npm-name -t breakdance` could give:
* freakout is avaliable
* harlem-shake is avaliable

**Comment by sindresorhus** [comment]
That's a fun idea. I like it.

**Comment by Robbie-Cook** [comment]
Thank you @sindresorhus . I agree -- it is important to not break existing users' workflows!

**Comment by Robbie-Cook** [comment]
@sindresorhus I have a PR here: https://github.com/sindresorhus/npm-name-cli/pull/23

**Comment by sindresorhus** [comment]
If anyone wants to work on this, see the initial attempt and feedback in https://github.com/sindresorhus/npm-name-cli/pull/23.
