### ISSUE TITLE
Misleading output for a taken name

### ISSUE THREAD

**Issue by prantlf** [sindresorhus/npm-name-cli#26]
When checking `estar` the output is the following:

    prantlf@macik:~ npm-name estar
    Error: Package `estar` doesn't exist
        at /Users/prantlf/.nvm/versions/node/v14.17.0/lib/node_modules/npm-name-cli/node_modules/package-json/index.js:62:11
        at processTicksAndRejections (internal/process/task_queues.js:95:5)
        at async squatter (/Users/prantlf/.nvm/versions/node/v14.17.0/lib/node_modules/npm-name-cli/node_modules/squatter/index.js:39:18)
        at async file:///Users/prantlf/.nvm/versions/node/v14.17.0/lib/node_modules/npm-name-cli/utilities.js:16:29
        at async Promise.all (index 0)
        at async checkNames (file:///Users/prantlf/.nvm/versions/node/v14.17.0/lib/node_modules/npm-name-cli/utilities.js:12:16)
        at async file:///Users/prantlf/.nvm/versions/node/v14.17.0/lib/node_modules/npm-name-cli/cli.js:79:19

Saying _"Package `estar` doesn't exist"_ is wrong, because although there is no package with the name `estar`, the existing package `es-tar` will prevent the name `estar` from being used by another package.

**Comment by sindresorhus** [comment]
// @sholladay FYI

**Comment by prantlf** [comment]
@sindresorhus, would you mind sharing your reason for closing this issue?

**Comment by sindresorhus** [comment]
Please look at the referenced commit. This was fixed.

**Comment by prantlf** [comment]
A, thanks! I am sorry I missed the link to the commit.
