### ISSUE TITLE
Throws error via CLI

### ISSUE THREAD

**Issue by eavichay** [sindresorhus/npm-name-cli#27]
- npm-name-cli v4.0.1
- node v12.16.3
- npm v 6.14.4

Throws error:
`Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: [MY_HOME_FOLDER]/.nvm/versions/node/v12.16.3/lib/node_modules/npm-name-cli/cli.js`

**Comment by sindresorhus** [comment]
You have an old version of Node.js 12. You need to upgrade to the latest minor.
