### ISSUE TITLE
Update to reflect new registry typosquat restrictions

### ISSUE THREAD

**Issue by ashleygwilliams** [sindresorhus/npm-name-cli#7]
recently the npm registry was updated to restrict available pkg names based on the presence of a pkg with a similar name whose diff is only punctuation. this is an awesome tool that helps people find pkg names, i'd like to make a PR to help account for this new registry restriction. if welcome, PR incoming.

for more details on the change, see this blog post: http://blog.npmjs.org/post/168978377570/new-package-moniker-rules

**Comment by ashleygwilliams** [comment]
gonna cross file this on `npm-name` as that appears to be what this cli tool uses under the hood

**Comment by sindresorhus** [comment]
Closing in favor of https://github.com/sindresorhus/npm-name/issues/15 as it should be fixed there.
