### ISSUE TITLE
can npm-name-cli expose API

### ISSUE THREAD

**Issue by adriatic** [sindresorhus/npm-name-cli#8]
Hello, Sindre

I am working on a tool I call Visual CLI, which presents a lot more user friendly (graphical) interface to (initially) **[Aurelia CLI](https://github.com/aurelia/cli)**. This tool is implemented as an Electron app and in addition to the standard set of services, like code generation based on user's input, it will assist with interactions with npm - like:

![image](https://user-images.githubusercontent.com/2712405/38335902-0409fa7a-382e-11e8-933c-8c859809ec39.png)

I was using the npm API for the above prototype and even tried some local npm database caching for better responsiveness. I liked your comments / answers to your own question on why to use npm-name-cli

> Nicer & simpler output
>
>npm search is only supported on npm 4, which is only bundled with Node.js 7.4+
>
>Squatter detection
>
>Performance

so, I thought it might make sense to have you see this note and hopefully get me your feedback.

**Comment by sindresorhus** [comment]
There already is an API, but it's a separate module: https://github.com/sindresorhus/npm-name
